import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faHeart,
  faCheckCircle,
  faUsers,
  faHome,
  faUser,
  faStar,
  faArrowRight,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faPlus,
  faMinus,
  faSearch,
  faCalendar,
  faClock,
  faLocationDot,
  faGraduationCap,
  faHandshake,
  faShieldAlt,
  faAward,
  faCertificate
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
library.add(
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faHeart,
  faCheckCircle,
  faUsers,
  faHome,
  faUser,
  faStar,
  faArrowRight,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faPlus,
  faMinus,
  faSearch,
  faCalendar,
  faClock,
  faLocationDot,
  faGraduationCap,
  faHandshake,
  faShieldAlt,
  faAward,
  faCertificate
);
